//AUTH ACTIONS
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL= 'AUTH_FAIL';
export const AUTH_FINISH= 'AUTH_FINISH';
export const AUTH_ERROR_CLEAN= 'AUTH_ERROR_CLEAN';
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT'
export const SET_EMAIL = "SET_EMAIL";
export const SET_PASSWORD = "SET_PASSWORD";
export const SHOW_PASSWORD = "SHOW_PASSWORD";

//REGISTER ACTIONS
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL= 'REGISTER_FAIL';
export const REGISTER_FINISH= 'REGISTER_FINISH';
export const REGISTER_ERROR_CLEAN= 'REGISTER_ERROR_CLEAN';
export const REGISTER_SET_NAME = "REGISTER_SET_NAME";
export const REGISTER_SET_PHONE = "REGISTER_SET_PHONE";
export const REGISTER_SET_EMAIL = "REGISTER_SET_EMAIL";
export const REGISTER_SET_PASSWORD = "REGISTER_SET_PASSWORD";
export const REGISTER_SHOW_PASSWORD = "REGISTER_SHOW_PASSWORD";